import type { AuthenticatedMedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import { MedusaError } from "@medusajs/framework/utils"
import { CUSTOMER_SUPPORT_MODULE } from "../../../../../../modules/customer-support"
import type { StoreMutateSupportConversation } from "../../../../../../modules/customer-support/contracts"
import type CustomerSupportModuleService from "../../../../../../modules/customer-support/service"
import { mutateCustomerSupportWorkflow } from "../../../../../../workflows/manage-customer-support"

const conversationView = (item: any) => ({ id: item.id, subject: item.subject, category: item.category, status: item.status, priority: item.priority, order_id: item.order_id, protocol_series_id: item.protocol_series_id, opened_at: item.opened_at, last_activity_at: item.last_activity_at })
export async function GET(req: AuthenticatedMedusaRequest, res: MedusaResponse) { const service = req.scope.resolve<CustomerSupportModuleService>(CUSTOMER_SUPPORT_MODULE); const [conversation] = await service.listSupportConversations({ id: req.params.conversationId, customer_id: req.auth_context.actor_id }, { take: 1 }); if (!conversation) throw new MedusaError(MedusaError.Types.NOT_FOUND, "Support conversation was not found"); const messages = await service.listSupportMessages({ conversation_id: conversation.id }, { order: { sent_at: "ASC" } }); const attachments = await service.listSupportAttachments({ conversation_id: conversation.id, status: "active" }); res.setHeader("Cache-Control", "private, no-store"); res.json({ conversation: { ...conversationView(conversation), messages: messages.map((message) => ({ id: message.id, sender: message.sender_type === "customer" ? "You" : message.sender_type === "system" ? "Automatic confirmation" : "Support", sender_type: message.sender_type, body: message.body, sent_at: message.sent_at, attachments: attachments.filter((item) => item.message_id === message.id).map((item) => ({ id: item.id, file_name: item.file_name, mime_type: item.mime_type, size_bytes: item.size_bytes })) })) } }) }
export async function POST(req: AuthenticatedMedusaRequest<StoreMutateSupportConversation>, res: MedusaResponse) { const { result } = await mutateCustomerSupportWorkflow(req.scope).run({ input: { ...req.validatedBody, customer_id: req.auth_context.actor_id, conversation_id: req.params.conversationId } }); res.setHeader("Cache-Control", "private, no-store"); res.json(result) }
