/**
 * @file    apps/storefront/src/lib/data/compound-protocols/index.ts
 * @module  CompoundProtocolsData (Storefront)
 * @purpose Registry of analytical compound and blend protocols.
 * @contracts
 *   API: GET /store/research-protocols
 */

import type { CompoundAnalyticalProtocol } from "./types.ts"

import allProtocolsRaw from "./all-protocols.json" with { type: "json" }

export type * from "./types.ts"
export * from "./category-1-tissue-repair.ts"
export * from "./category-2-metabolic.ts"
export * from "./category-3-gh-axis.ts"
export * from "./category-4-longevity.ts"
export * from "./category-5-neuro.ts"
export * from "./category-6-immune-sexual.ts"
export * from "./category-7-blends.ts"
export * from "./category-8-supplies.ts"

/**
 * Master Registry of all 81 Verified Analytical Compound & Blend Protocols.
 * Sourced directly from all-protocols.json (generated by Peptides Studio PIM publisher).
 */
export const ALL_COMPOUND_PROTOCOLS: CompoundAnalyticalProtocol[] = allProtocolsRaw as unknown as CompoundAnalyticalProtocol[]


/**
 * Filter protocols by clinical/pharmacological category
 */
export function getProtocolsByCategory(
  category: CompoundAnalyticalProtocol["category"]
): CompoundAnalyticalProtocol[] {
  return ALL_COMPOUND_PROTOCOLS.filter((p) => p.category === category)
}

/**
 * Filter protocols by catalog availability
 */
export function getProtocolsByCatalogStatus(
  status: "in_catalog" | "reference_only"
): CompoundAnalyticalProtocol[] {
  return ALL_COMPOUND_PROTOCOLS.filter((p) => p.catalogStatus === status)
}

/**
 * Retrieve protocol by strict ID
 */
export function getProtocolById(id: string): CompoundAnalyticalProtocol | undefined {
  const normalized = id.toLowerCase().trim()
  return ALL_COMPOUND_PROTOCOLS.find((p) => p.id.toLowerCase() === normalized)
}
