import type { CompoundAnalyticalProtocol } from "./types.ts"
import { CATEGORY_1_TISSUE_REPAIR_PROTOCOLS } from "./category-1-tissue-repair.ts"
import { CATEGORY_2_METABOLIC_INCRETIN_PROTOCOLS } from "./category-2-metabolic.ts"
import { CATEGORY_3_GH_AXIS_PROTOCOLS } from "./category-3-gh-axis.ts"
import { CATEGORY_4_LONGEVITY_PROTOCOLS } from "./category-4-longevity.ts"
import { CATEGORY_5_NEURO_PROTOCOLS } from "./category-5-neuro.ts"
import { CATEGORY_6_IMMUNE_SEXUAL_PROTOCOLS } from "./category-6-immune-sexual.ts"
import { CATEGORY_7_BLENDS_PROTOCOLS } from "./category-7-blends.ts"
import { CATEGORY_8_SUPPLIES_PROTOCOLS } from "./category-8-supplies.ts"

import allProtocolsRaw from "./all-protocols.json" with { type: "json" }

export type * from "./types.ts"
export * from "./category-1-tissue-repair.ts"
export * from "./category-2-metabolic.ts"
export * from "./category-3-gh-axis.ts"
export * from "./category-4-longevity.ts"
export * from "./category-5-neuro.ts"
export * from "./category-6-immune-sexual.ts"
export * from "./category-7-blends.ts"
export * from "./category-8-supplies.ts"

/**
 * Master Registry of all 81 Verified Analytical Compound & Blend Protocols.
 * Sourced directly from all-protocols.json (generated by Peptides Studio PIM publisher).
 */
export const ALL_COMPOUND_PROTOCOLS: CompoundAnalyticalProtocol[] = allProtocolsRaw as unknown as CompoundAnalyticalProtocol[]


/**
 * Filter protocols by clinical/pharmacological category
 */
export function getProtocolsByCategory(
  category: CompoundAnalyticalProtocol["category"]
): CompoundAnalyticalProtocol[] {
  return ALL_COMPOUND_PROTOCOLS.filter((p) => p.category === category)
}

/**
 * Filter protocols by catalog availability
 */
export function getProtocolsByCatalogStatus(
  status: "in_catalog" | "reference_only"
): CompoundAnalyticalProtocol[] {
  return ALL_COMPOUND_PROTOCOLS.filter((p) => p.catalogStatus === status)
}

/**
 * Retrieve protocol by strict ID
 */
export function getProtocolById(id: string): CompoundAnalyticalProtocol | undefined {
  const normalized = id.toLowerCase().trim()
  return ALL_COMPOUND_PROTOCOLS.find((p) => p.id.toLowerCase() === normalized)
}
