import { ProtocolCalculator } from "./calculator"
import type { CustomerResearchProtocol } from "@lib/data/research-protocols"

export default function FullProtocol({ protocol }: { protocol: CustomerResearchProtocol }) {
  const content = protocol.content
  return <div>
    <header className="rounded-xl border border-ui-border-base bg-white p-6">
      <p className="text-xs font-semibold uppercase tracking-wide text-ui-fg-interactive">Current protected protocol</p>
      <h1 className="mt-2 text-3xl font-semibold">{content.compound_name || protocol.title}</h1>
      <p className="mt-2 text-sm text-ui-fg-subtle">Revision {protocol.revision}{content.product_format ? ` · ${content.product_format}` : ""}</p>
      {content.short_introduction ? <p className="mt-4 max-w-3xl text-sm leading-6 text-ui-fg-subtle">{content.short_introduction}</p> : null}
    </header>
    {content.quick_reference.length ? <section className="mt-6 grid gap-3 small:grid-cols-2 large:grid-cols-3">{content.quick_reference.map((item) => <article key={item.key} className="rounded-xl border border-ui-border-base bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-ui-fg-subtle">{item.label}</p><p className="mt-2 text-lg font-semibold">{item.value}</p>{item.description ? <p className="mt-2 text-sm text-ui-fg-subtle">{item.description}</p> : null}</article>)}</section> : null}
    {content.calculator.enabled ? <div className="mt-8"><ProtocolCalculator configuration={content.calculator} /></div> : null}
    {content.protocol_levels.map((level) => <section key={level.key} className="mt-8 rounded-xl border border-ui-border-base bg-white p-6"><h2 className="text-xl font-semibold">{level.title}</h2>{level.summary ? <p className="mt-2 text-sm text-ui-fg-subtle">{level.summary}</p> : null}<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b border-ui-border-base text-ui-fg-subtle"><th className="px-3 py-2">Period</th><th className="px-3 py-2">Amount</th><th className="px-3 py-2">Frequency</th><th className="px-3 py-2">Notes</th></tr></thead><tbody>{level.rows.map((row, index) => <tr key={row.row_key || `${level.key}-${index}`} className="border-b border-ui-border-base last:border-0"><td className="px-3 py-3">{row.period}</td><td className="px-3 py-3 font-medium">{row.amount} {row.unit}</td><td className="px-3 py-3">{row.frequency}</td><td className="px-3 py-3 text-ui-fg-subtle">{row.notes || "—"}</td></tr>)}</tbody></table></div></section>)}
    {content.reference_quantities.length ? <section className="mt-8 rounded-xl border border-ui-border-base bg-white p-6"><h2 className="text-xl font-semibold">Reference quantities</h2><div className="mt-4 grid gap-3 small:grid-cols-2">{content.reference_quantities.map((item, index) => <div key={`${item.label}-${index}`} className="rounded-lg bg-ui-bg-subtle p-4"><p className="font-medium">{item.label}: {item.value} {item.unit}</p>{item.concentration ? <p className="mt-1 text-sm text-ui-fg-subtle">Concentration: {item.concentration}</p> : null}{item.conversion_basis ? <p className="mt-1 text-sm text-ui-fg-subtle">Conversion: {item.conversion_basis}</p> : null}<p className="mt-2 text-sm text-ui-fg-subtle">{item.laboratory_purpose}</p></div>)}</div></section> : null}
    {[{ title: "Research purpose", body: content.research_purpose }, { title: "Intended application", body: content.intended_application }, { title: "Preparation and handling", body: content.preparation_and_handling }, { title: "Research procedure", body: content.research_procedure }, { title: "Storage and disposal", body: content.storage_and_disposal }].filter((item) => item.body).map((item) => <section key={item.title} className="mt-8 rounded-xl border border-ui-border-base bg-white p-6"><h2 className="text-xl font-semibold">{item.title}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-ui-fg-subtle">{item.body}</p></section>)}
    {content.sections.filter((section) => section.visible).sort((a, b) => a.position - b.position).map((section) => <section key={section.key} className="mt-8 rounded-xl border border-ui-border-base bg-white p-6"><h2 className="text-xl font-semibold">{section.title}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-ui-fg-subtle">{section.body}</p></section>)}
    {content.faqs.length ? <section className="mt-8 rounded-xl border border-ui-border-base bg-white p-6"><h2 className="text-xl font-semibold">Frequently asked questions</h2><div className="mt-4 space-y-3">{content.faqs.sort((a, b) => a.position - b.position).map((faq) => <details key={faq.key} className="rounded-lg border border-ui-border-base p-4"><summary className="cursor-pointer font-medium">{faq.question}</summary><p className="mt-3 text-sm leading-6 text-ui-fg-subtle">{faq.answer}</p></details>)}</div></section> : null}
    <div className="mt-8 rounded-xl border border-ui-border-base bg-ui-bg-subtle p-5 text-sm text-ui-fg-subtle">{content.disclaimer}</div>
  </div>
}
