import {
  RESEARCH_PROTOCOL_REQUIRED_DISCLAIMER,
  type ResearchProtocolMutationBody,
} from "../compounded-products/research-protocol-types"

export const emptyResearchProtocol: ResearchProtocolMutationBody = {
  title: "",
  summary: null,
  purpose: null,
  evidence_scope: "formulation",
  content: {
    compound_name: null,
    short_introduction: null,
    product_format: null,
    category: null,
    research_use_label: "Research use only",
    last_reviewed_at: null,
    quick_reference: [],
    calculator: {
      enabled: false,
      title: "Protocol calculator",
      default_compound_mass: null,
      compound_mass_unit: "mg",
      default_final_volume_ml: null,
      default_target_amount: null,
      target_amount_unit: "mcg",
      iu_per_mg: null,
      device_volume_ml: null,
      device_label: null,
      rounding_precision: 2,
      instructions: null,
    },
    protocol_levels: [],
    sections: [],
    faqs: [],
    research_purpose: "",
    intended_application: null,
    explicit_exclusions: null,
    reference_quantities: [],
    materials_and_equipment: [],
    preparation_and_handling: "",
    research_procedure: "",
    storage_and_disposal: "",
    references: [],
    disclaimer: RESEARCH_PROTOCOL_REQUIRED_DISCLAIMER,
  },
}
