import { sdk } from "@lib/config"
import LocalizedClientLink from "@modules/common/components/localized-client-link"
import { ProtocolCalculator } from "@modules/research-protocols/calculator"
import type { ResearchProtocolContent } from "@modules/research-protocols/types"
import { notFound } from "next/navigation"

type Props = { params: Promise<{ token: string }> }

export default async function OrderProtocolAccessPage({ params }: Props) {
  const { token } = await params
  const protocol = await sdk.client.fetch<{ protocol: { title: string; handle: string; revision: number; issued_at: string; current_revision: number | null; has_newer_revision: boolean; content: ResearchProtocolContent } }>(`/store/research-protocol-access/${encodeURIComponent(token)}`, { method: "GET", cache: "no-store" }).then((response) => response.protocol).catch(() => null)
  if (!protocol) notFound()
  const content = protocol.content
  return <main className="content-container py-12 small:py-20"><div className="max-w-4xl"><p className="text-small-semi uppercase tracking-wider text-ui-fg-interactive">Order-linked protocol</p><h1 className="mt-3 text-3xl-semi text-ui-fg-base">{content.compound_name || protocol.title}</h1><p className="mt-3 text-base-regular text-ui-fg-subtle">Revision {protocol.revision} · Preserved for this order</p>{protocol.has_newer_revision ? <div className="mt-5 rounded-rounded border border-ui-border-base bg-ui-bg-subtle p-4"><p className="text-small-semi text-ui-fg-base">A newer revision is available.</p><p className="mt-1 text-small-regular text-ui-fg-subtle">This page remains on the version associated with your order.</p><LocalizedClientLink href={`/research-protocols/${protocol.handle}`} className="mt-2 inline-block text-small-semi text-ui-fg-interactive">View current revision {protocol.current_revision}</LocalizedClientLink></div> : null}{content.short_introduction ? <p className="mt-5 text-base-regular">{content.short_introduction}</p> : null}</div>{content.quick_reference.length ? <section className="mt-8 grid gap-3 small:grid-cols-2 large:grid-cols-3">{content.quick_reference.map((item) => <div key={item.key} className="rounded-rounded border border-ui-border-base p-5"><p className="text-small-semi text-ui-fg-subtle">{item.label}</p><p className="mt-2 text-large-semi">{item.value}</p>{item.description ? <p className="mt-2 text-small-regular text-ui-fg-subtle">{item.description}</p> : null}</div>)}</section> : null}{content.calculator.enabled ? <div className="mt-8"><ProtocolCalculator configuration={content.calculator} /></div> : null}{content.protocol_levels.map((level) => <section key={level.key} className="mt-10"><h2 className="text-2xl-semi">{level.title}</h2>{level.summary ? <p className="mt-2 text-base-regular text-ui-fg-subtle">{level.summary}</p> : null}<div className="mt-4 grid gap-2">{level.rows.map((row, index) => <div key={`${level.key}-${index}`} className="grid gap-2 rounded-rounded border border-ui-border-base p-4 small:grid-cols-3"><span>{row.period}</span><span>{row.amount} {row.unit}</span><span>{row.frequency}</span></div>)}</div></section>)}{content.sections.filter((section) => section.visible).sort((a, b) => a.position - b.position).map((section) => <section key={section.key} className="mt-10 max-w-4xl"><h2 className="text-2xl-semi">{section.title}</h2><p className="mt-3 whitespace-pre-wrap text-base-regular text-ui-fg-subtle">{section.body}</p></section>)}<div className="mt-12 rounded-rounded border border-ui-border-base bg-ui-bg-subtle p-5"><p className="text-small-regular">{content.disclaimer}</p></div></main>
}
